export const GAME_SETTINGS = {
  DEFAULT_NUMBER_OF_ORBS: 2000,
  DEFAULT_PLAYER_RADIUS: 10,
  DEFAULT_PLAYER_SPEED: 2,
  DEFAULT_PLAYER_ZOOM: 1.5,
  DEFAULT_PLAYER_SCORE: 0,
  DEFAULT_NUMBER_OF_BOT_PLAYERS: 10,
  MAP_HEIGHT: 5000,
  MAP_WIDTH: 5000,
  ORB_RADIUS: 5,
  FPS: 60,
} as const
