export const GAME_SETTINGS = {
  DEFAULT_NUMBER_OF_ORBS: 500,
  DEFAULT_PLAYER_SPEED: 3,
  DEFAULT_PLAYER_SIZE: 6,
  DEFAULT_ORB_SIZE: 5,
  DEFAULT_ZOOM: 1.5,
  MAP_WIDTH: 500,
  MAP_HEIGHT: 500,
} as const
